version: '3.7'
services:
  mysql:
    image: yobasystems/alpine-mariadb
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    expose:
      - 3306
    restart: always
    networks:
      back:
        ipv4_address: ${NETWORK_BASE}.10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPADMIN_PORT}:80"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306
    networks:
      back:
        ipv4_address: ${NETWORK_BASE}.12

  cache:
    image: redis:alpine
    hostname: redis
    networks:
      back:
        ipv4_address: ${NETWORK_BASE}.7

  php:
    build:
      context: ./config/php
      args:
        ENVIROMENT: ${ENVIROMENT}
        WEB_USER: ${WEB_USER}
    container_name: weblogic
    volumes:
      - sock:/sock
      # - ./config/php/ext-xdebug.ini:/usr/local/etc/php/conf.d/ext-xdebug.ini
      - type: volume
        source: app_data
        target: /var/www/html
    env_file: .env
    depends_on:
      - mysql
      - cache
    networks:
      back:
        ipv4_address: ${NETWORK_BASE}.18

  web:
    build:
      context: ./config/nginx
      args:
        WEB_USER: ${WEB_USER}
    container_name: web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - sock:/sock
      - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/ssl:/etc/nginx/ssl
      - ./config/nginx/auth:/etc/nginx/auth
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
      - type: volume
        source: app_data
        target: /var/www/html
    depends_on:
      - php
    networks:
      back:
        ipv4_address: ${NETWORK_BASE}.3

  certbot:
    build:
      context: ./config/certbot
      args:
        ADMIN_EMAI: ${ADMIN_EMAI}
        HOSTNAME: ${HOSTNAME}
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - app_data:/var/www/html
    depends_on:
      - web

volumes:
  certbot-etc:
  certbot-var:
    driver: local

  mysqldata:
    driver: local

  app_data:
    driver: local
    driver_opts:
      type: none
      device: "${ROOT_PROJECT}src"
      o: bind

  sock:
    driver: local

  dhparam:
    driver: local
    driver_opts:
      type: none
      device: "${ROOT_PROJECT}config/dhparam"
      o: bind

networks:
  back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_BASE}.0/24
