version: '3.7'
services:
  web:
    build:
      context: ./config/nginx
      args:
        WEB_USER: ${WEB_USER}
    container_name: webserver
    restart: unless-stopped 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - sock:/sock
      - ./config/nginx/sites-enabled/default.conf:/etc/nginx/sites-enabled/default.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/ssl:/etc/nginx/ssl
      - ./config/nginx/auth:/etc/nginx/auth
      - type: volume
        source: app_data
        target: /var/www/html
    networks:
      - front
      - back

  php:
    build:
      context: ./config/php
      args:
        ENVIROMENT: ${ENVIROMENT}
        WEB_USER: ${WEB_USER}
    container_name: weblogic
    volumes:
      - sock:/sock
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      # - ./config/php/ext-xdebug.ini:/usr/local/etc/php/conf.d/ext-xdebug.ini
      - type: volume
        source: app_data
        target: /var/www/html
    env_file: .env
    depends_on:
      - mysql
      - cache
    networks:
      - back
  
  mysql:
    image: yobasystems/alpine-mariadb
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    expose:
      - 3306
    restart: always
    networks:
      - back

  cache:
    image: redis:latest
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPADMIN_PORT}:80"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306
    networks:
      - front
      - back

volumes:
  mysqldata:
    driver: local
  app_data:
    driver: local
    driver_opts:
      type: none
      device: "${ROOT_PROJECT}src"
      o: bind
  sock:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge
